#encoding: utf-8
require 'spec_helper'
describe Netfilter::Ip6Tables do
  describe "Class Methods" do
    describe "parse" do
      it "should properly parse the current system's iptables" do
        Netfilter::Ip6Tables.stub(:execute).and_return <<EOT
# Generated by iptables-save v1.4.12 on Wed Sep 18 14:15:43 2013
*nat
:PREROUTING ACCEPT [920364:135062514]
:INPUT ACCEPT [62393:3917616]
:OUTPUT ACCEPT [59623:4116943]
:POSTROUTING ACCEPT [640454:41456220]
-A PREROUTING -d 185.14.157.109/32 -p tcp -m tcp --dport 5900 -j DNAT --to-destination 10.0.0.8:5921
-A PREROUTING -d 185.14.157.123/32 -p tcp -m tcp --dport 5900 -j DNAT --to-destination 10.0.0.8:5923
COMMIT
# Completed on Wed Sep 18 14:15:43 2013
# Generated by iptables-save v1.4.12 on Wed Sep 18 14:15:43 2013
*filter
:INPUT DROP [5647:1842222]
:FORWARD ACCEPT [267259:341060431]
:OUTPUT ACCEPT [3936250:18401515934]
:guest15865-1-i - [0:0]
:guest19265-1-i - [0:0]
:guest592991-1-i - [0:0]
-A INPUT -d 10.0.0.8/32 -p tcp -m tcp --dport 5920 -j DROP
-A INPUT -s 10.0.0.0/8 -d 10.0.0.0/8 -j ACCEPT
-A INPUT -d 127.0.0.0/8 -i lo -j ACCEPT
-A INPUT -s 212.224.87.102/32 -p tcp -m tcp --dport 4949 -j ACCEPT
-A INPUT -p tcp -m tcp --dport 22 -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A INPUT -m conntrack --ctstate INVALID -j DROP
-A INPUT -d 10.0.0.8/32 -p tcp -m tcp --dport 5921 -j ACCEPT
-A INPUT -d 10.0.0.8/32 -p tcp -m tcp --dport 5923 -j ACCEPT
-A FORWARD -m physdev --physdev-out tap15866 --physdev-is-bridged -j guest15865-1-i
-A FORWARD -m physdev --physdev-out tap19266 --physdev-is-bridged -j guest19265-1-i
-A FORWARD -m physdev --physdev-out tap592992 --physdev-is-bridged -j guest592991-1-i
-A guest15865-1-i -j RETURN
-A guest19265-1-i -m conntrack --ctstate RELATED,ESTABLISHED -j RETURN
-A guest19265-1-i -p tcp -m tcp --dport 80 -j RETURN
-A guest19265-1-i -p tcp -m tcp --dport 22 -j RETURN
-A guest19265-1-i -p tcp -m tcp --dport 443 -j RETURN
-A guest19265-1-i -s 185.14.157.0/24 -p udp -m udp --dport 67 -j RETURN
-A guest19265-1-i -s 185.14.157.0/24 -p udp -m udp --dport 68 -j RETURN
-A guest19265-1-i -p tcp -j DROP
-A guest19265-1-i -p udp -j DROP
-A guest19265-1-i -j RETURN
-A guest592991-1-i -j RETURN
COMMIT
# Completed on Wed Sep 18 14:15:43 2013
EOT
        data =  Netfilter::Ip6Tables.parse
        data.should eq(
          "nat" => {
            "PREROUTING" => [
              "-d 185.14.157.109/32 -p tcp -m tcp --dport 5900 -j DNAT --to-destination 10.0.0.8:5921",
              "-d 185.14.157.123/32 -p tcp -m tcp --dport 5900 -j DNAT --to-destination 10.0.0.8:5923"
            ]
          },
          "filter" => {
            "INPUT" => [
              "-d 10.0.0.8/32 -p tcp -m tcp --dport 5920 -j DROP",
              "-s 10.0.0.0/8 -d 10.0.0.0/8 -j ACCEPT",
              "-d 127.0.0.0/8 -i lo -j ACCEPT",
              "-s 212.224.87.102/32 -p tcp -m tcp --dport 4949 -j ACCEPT",
              "-p tcp -m tcp --dport 22 -j ACCEPT",
              "-p icmp -j ACCEPT",
              "-m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT",
              "-m conntrack --ctstate INVALID -j DROP",
              "-d 10.0.0.8/32 -p tcp -m tcp --dport 5921 -j ACCEPT",
              "-d 10.0.0.8/32 -p tcp -m tcp --dport 5923 -j ACCEPT"
            ],
            "FORWARD" => [
              "-m physdev --physdev-out tap15866 --physdev-is-bridged -j guest15865-1-i",
              "-m physdev --physdev-out tap19266 --physdev-is-bridged -j guest19265-1-i",
              "-m physdev --physdev-out tap592992 --physdev-is-bridged -j guest592991-1-i"
            ],
            "guest15865-1-i" => [
              "-j RETURN"
            ],
            "guest19265-1-i" => [
              "-m conntrack --ctstate RELATED,ESTABLISHED -j RETURN",
              "-p tcp -m tcp --dport 80 -j RETURN",
              "-p tcp -m tcp --dport 22 -j RETURN",
              "-p tcp -m tcp --dport 443 -j RETURN",
              "-s 185.14.157.0/24 -p udp -m udp --dport 67 -j RETURN",
              "-s 185.14.157.0/24 -p udp -m udp --dport 68 -j RETURN",
              "-p tcp -j DROP",
              "-p udp -j DROP",
              "-j RETURN"
            ],
            "guest592991-1-i" => [
              "-j RETURN"
            ],
          },
        )
      end
    end
  end
end
